# Tech Docs configuration
# https://github.com/alphagov/tech-docs-gem/blob/main/example/config/tech-docs.yml

# Host to use for canonical URL generation (without trailing slash)
host: docs.data-community.publishing.service.gov.uk

# Header-related options
show_govuk_logo: false
service_name: Data Community Technical Documentation
service_link: https://docs.data-community.publishing.service.gov.uk
phase:

# Links to show on right-hand-side of header
header_links:
  About: https://docs.data-community.publishing.service.gov.uk
  Get Started: https://docs.data-community.publishing.service.gov.uk
  Documentation: /
  Support: https://docs.data-community.publishing.service.gov.uk

# Enables search functionality. This indexes pages only and is not recommended for single-page sites.
enable_search: true

# Google Analytics 4 using Google Tag Manager (e.g GTM-XXXXXXXX)
ga4_gtm_tracking_id: GTM-WVQKH9TT

# Enable multipage navigation in the sidebar
multipage_nav: true

# Enable collapsible navigation in the sidebar
collapsible_nav: true

# Table of contents depth â€“ how many levels to include in the table of contents.
# If your ToC is too long, reduce this number and we'll only show higher-level
# headings.
max_toc_heading_level: 1

# Prevent robots from indexing (e.g. whilst in development)
prevent_indexing: false

show_contribution_banner: true
github_repo: alphagov/data-community-tech-docs
github_branch: main

# Ownership for page reviews
default_owner_slack: '#insights-and-analytics-alerts'
owner_slack_workspace: gds
